---
id: Cache
name: Cache
full: Caching library
description: >
  A simple, functional caching API, with the option to store the cached data on
  the filesystem, in one of the PHP opcode cache systems (APC, eAcclerator,
  XCache), Memcache, MongoDB, Redis, user session, an SQL table, or a
  combination of these.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Cache
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: true
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: true
    role: lead
version:
  release: 2.5.6
  api: 2.5.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Compress_Fast: ^1
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Util: ^2
    ext:
      hash: '*'
  optional:
    pear:
      pear.horde.org/Horde_Db: ^2.1
      pear.horde.org/Horde_HashTable: ^1
      pear.horde.org/Horde_Log: ^2
      pear.horde.org/Horde_Memcache: ^2
      pear.horde.org/Horde_Mongo: ^1
      pecl.php.net/APC:
        version: ^3.1.1
        providesextension: apc
    ext:
      eaccelerator: 0.9.5
      xcache: '*'
